### PR TITLE
Improve groundwork scheduling

### PR DESCRIPTION
**Pull request by csweichel**
This PR improves the behaviour of `/schedule`:
- if the Scheduled column fewer than `freeForAllLimit` cards, the command succeeds for everyone
- if the Scheduled column has more than `totalLimit` cards, it succeeds for no one
- if the issue has any of the priority labels it's placed on top, otherwise at the bottom

The groundwork and projectmanager pods are already built and cycled, but need to be restarted once this is merged.

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/11#" title="Author self-approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by leodido — APPROVED** [review]
V V V cool!

LGTM 🔥

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: b9a308ea57b62fe16d20703212c1ec4aed2250de</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/11#" title="Author self-approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitbot/pull/11#pullrequestreview-711469489" title="Approved">leodido</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [csweichel,leodido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
@csweichel: Updated the following 2 configmaps:
 * `projectmanager` configmap in namespace `prow` at cluster `default` using the following files:
   - key `projectmanager.yaml` using file `config/projectmanager.yaml`
 * `groundwork` configmap in namespace `prow` at cluster `default` using the following files:
   - key `groundwork.yaml` using file `config/groundwork.yaml`


<details>

In response to [this](https://github.com/gitpod-io/gitbot/pull/11):

>This PR improves the behaviour of `/schedule`:
>- if the Scheduled column fewer than `freeForAllLimit` cards, the command succeeds for everyone
>- if the Scheduled column has more than `totalLimit` cards, it succeeds for no one
>- if the issue has any of the priority labels it's placed on top, otherwise at the bottom
>
>The groundwork and projectmanager pods are already built and cycled, but need to be restarted once this is merged.


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
