### PR TITLE
Add team self-hosted to custom labels

### PR DESCRIPTION
**Pull request by MrSimonEmms**
## Description

Add team self-hosted to the bot. In response to https://github.com/gitpod-io/gitpod/issues/7571#issuecomment-1011181130

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **meysholdt** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @meysholdt` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mads-hartmann — APPROVED** [review]
@MrSimonEmms The changes look good, but how this works is all going to change soon, see [Using GitHub for PR review automation](https://www.notion.so/gitpod/Using-GitHub-for-PR-review-automation-35d5e77a7e4b4999a72b5eef2458f636) - the plan is to execute on that RFC next week ☺️

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: a29fa6f3dd410b10c22e64849efbb7063701eb84</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/63#pullrequestreview-851410002" title="Approved">mads-hartmann</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [mads-hartmann]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
@MrSimonEmms: Updated the `customlabels` configmap in namespace `prow` at cluster `default` using the following files:
 - key `customlabels.yaml` using file `config/customlabels.yaml`

<details>

In response to [this](https://github.com/gitpod-io/gitbot/pull/63):

>## Description
>
>Add team self-hosted to the bot. In response to https://github.com/gitpod-io/gitpod/issues/7571#issuecomment-1011181130
>
>## How to test
>
>
>## Release Notes
>
>```release-note
>NONE
>```
>
>## Documentation
>
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
