### PR TITLE
Use rebase for ops repository

### PR DESCRIPTION
**Pull request by mads-hartmann**
## Description

We want to use rebase as the merge method like the other repository.

## Related Issue(s)

Part of gitpod-io/ops/issues/116

## How to test

N/A

## Release Notes

```release-note
NONE
```

## Documentation

N/A

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mads-hartmann** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by meysholdt — APPROVED** [review]

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 759ac394489e89eebc234a6e62e3300ca19460ea</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/61#pullrequestreview-827639932" title="Approved">meysholdt</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [meysholdt]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
@mads-hartmann: Updated the `config` configmap in namespace `prow` at cluster `default` using the following files:
 - key `config.yaml` using file `config/config.yaml`

<details>

In response to [this](https://github.com/gitpod-io/gitbot/pull/61):

>## Description
>
>
>We want to use rebase as the merge method like the other repository.
>
>## Related Issue(s)
>
>Part of gitpod-io/ops/issues/116
>
>## How to test
>
>
>N/A
>
>## Release Notes
>
>```release-note
>NONE
>```
>
>## Documentation
>
>
>N/A


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
