### PR TITLE
plugins/deployed-labeler: New plugin that labels deployed PRs

### PR DESCRIPTION
**Pull request by ArthurSens**
## Description

It receives "commit" and "team" as parameters, then adds the label `deployed` to all pull requests(that has the label `team: <team-parameter>`) associated with a merged commit in the commit tree.

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/159

## How to test

Retrieve hmac and github token from our Prow cluster and run `main.go`  with:
```
go run main.go -hmac=hmac --github-token-path=token
```

Then on a new terminal run the command: 
```
curl -XPOST 'localhost:8080/deployed?commit=0a483885ff9a6ff1149c0388d1751635fd8cd788&team=test'
```

It should return 2 arrays, where the first is the URL of all pull requests that were successfully labeled and the second is an array of errors that may have occurred in the process.

E.g.:
image

## Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by csweichel** [comment]
Awesome! The bot correctly adds the deployed label to the matching PRs. Things that are still missing:
- `deployed` label when all `deployed: X` labels are present for all `team: X` labels
- re-adds the labels over and over again. This will eat up the API call limits, is slow and noisy on the PR.

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/47#issuecomment-955750275" title="LGTM">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 7b5cd8e3b4eaf5b1e233e626a5d49ce3d4be8721</details>

**Pull request merged**
