### PR TITLE
fix: disable self approval

### PR DESCRIPTION
**Pull request by leodido**
By looking at the [implementation code](https://github.com/kubernetes/test-infra/blob/9901b188a14600d62641c14c0d9003dae9fbdf9b/prow/plugins/config.go#L320) I noticed a negation.

Thus, since we do **not** want the authors to automatically self-approve their PRs (as per internal discussions), we need to revert those two values. Basically, specifying them as `false` is like not specifying them at all (ie., `nil`).

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/15#" title="Author self-approved">leodido</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [leodido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by leodido** [comment]
If this PR gets merged in the results for PRs in gitpod and gitbot (this repo) will be like the one in this screenshot from https://github.com/gitpod-io/gitpod-test-repo/pull/115

image

**Comment by csweichel** [comment]
does that mean that after the LGTM by reviewers, the author of the PR would need to `/approve`?

**Comment by leodido** [comment]
> does that mean that after the LGTM by reviewers, the author of the PR would need to `/approve`?

Nope, because the LGTM will also automatically approve the PR.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 613c5bbcd2267a5957093f4e36ea2bf297f7356f</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/15#issuecomment-888508063" title="LGTM">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitbot/pull/15#" title="Author self-approved">leodido</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [csweichel,leodido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
New changes are detected. LGTM label has been removed.

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: ab47340668b9878f286a37e73cb6406c03d3bb3e</details>

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/15#issuecomment-889137345" title="LGTM">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitbot/pull/15#" title="Author self-approved">leodido</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [csweichel,leodido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
@leodido: Updated the `plugins` configmap in namespace `prow` at cluster `default` using the following files:
 - key `plugins.yaml` using file `config/plugins.yaml`

<details>

In response to [this](https://github.com/gitpod-io/gitbot/pull/15):

>By looking at the [implementation code](https://github.com/kubernetes/test-infra/blob/9901b188a14600d62641c14c0d9003dae9fbdf9b/prow/plugins/config.go#L320) I noticed a negation.
>
>Thus, since we do **not** want the authors to automatically self-approve their PRs (as per internal discussions), we need to revert those two values. Basically, specifying them as `false` is like not specifying them at all (ie., `nil`).


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
