### PR TITLE
Require an associated issue for PRs on gitpod-io

### LINKED ISSUE #9: Require associated issues?
During our internal sync @svenefftinge brought up considerations whether we may want or want not to require issues associated with PRs.

In case we want (for all repos or for a subset of them) this we can do it with the `issue_required` field of the `approve` plugin.

https://github.com/kubernetes/test-infra/blob/e465d4fd9d61446fd3c7557d73c9f237b0ad1cf9/prow/plugins/config.go#L295

### PR DESCRIPTION
**Pull request by csweichel**
fixes #9

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/12#" title="Author self-approved">csweichel</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [csweichel]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by leodido — APPROVED** [review]

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/12#" title="Author self-approved">csweichel</a>*, *<a href="https://github.com/gitpod-io/gitbot/pull/12#pullrequestreview-714576959" title="Approved">leodido</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [csweichel,leodido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
LGTM label has been added.  <details>Git tree hash: 02db0fcbb236c5c1749bc8936a9138757f640f09</details>

**Comment by roboquat** [comment]
@csweichel: Updated the `plugins` configmap in namespace `prow` at cluster `default` using the following files:
 - key `plugins.yaml` using file `config/plugins.yaml`

<details>

In response to [this](https://github.com/gitpod-io/gitbot/pull/12):

>fixes #9 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
