### PR TITLE
update(config): do not implicitly assume author self approves

### PR DESCRIPTION
**Pull request by leodido**

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/5#" title="Author self-approved">leodido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [leodido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by csweichel** [comment]
if we disable this, does that mean that for each PR we need two folks: one to approve, and one to review?

**Comment by leodido** [comment]
> if we disable this, does that mean that for each PR we need two folks: one to approve, and one to review?
> 
> Personally I don't mind the self-approval so much - it's actually quite convenient :)

Nope, that's a blunderbuss option as far as I remember :)

Tomorrow I'll double check anyways

**Comment by roboquat** [comment]
@leodido: Updated the `plugins` configmap in namespace `prow` at cluster `default` using the following files:
 - key `plugins.yaml` using file `config/plugins.yaml`

<details>

In response to [this](https://github.com/gitpod-io/gitbot/pull/5):

>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
