### PR TITLE
Remove obsolete Prow plugins

### PR DESCRIPTION
**Pull request by mads-hartmann**
## Description

Once we have migrated to using GitHub for PR Review automation ([epic](https://github.com/gitpod-io/ops/issues/838)) we can remove a lot of the plugins that we current have from Prow.

- assign (/assign)
- blunderbuss (was supposed to automate review requests but was disabled)
- verify-owners (would add the label `do-not-merge/invalid-owners-file` if the OWNERS or OWNER_ALIASES files were invalid)
- owners-label (Would add labels based on owner)
- approve (/approve which would add the approved label)
- lgtm (/lgtm which would add the lgtm label)
- groundwork (I believe the /schedule and other groundwork related commands we no longer use)
- projectmanager (I believe this would move issues around, but we have since moved to the new GH Projects and don't rely on this)
- goose, cat, and dog (/woof, /meow, and /honk)
- heart (was unused, we never configured it)
- yuks (/joke)
- label (would allow .e.g `/kind bug` - instead use the native GH feature and just press 'l' when viewing a PR or issue which allows you to add labels) 
- willkommen (was never used in gitpod-io/gitpod I believe)
- customlabels (the labels used in gitpod-io/gitpod seems to no longer be relevant as we assign team labels based on PR Reviwers now)
- observer (From Jan: "The observer was an early attempt to measure the throughput of our deployment pipeline. It's been obsoleted by Athenian")
- help (/help command which added 'help wanted' or 'good first issue')

## Related Issue(s)

Fixes https://github.com/gitpod-io/ops/issues/845

## How to test

Merge and manually delete any k8s resources lingering around.

## Release Notes

```release-note
NONE
```

## Documentation

N/A

### CODE REVIEW

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mads-hartmann** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mads-hartmann** [comment]
@JanKoehnlein or @csweichel do you know what the observer was doing? Is it okay to remove?

**Comment by JanKoehnlein** [comment]
The observer was an early attempt to measure the throughput of our deployment pipeline. It's been obsoleted by Athenian

**Comment by mads-hartmann** [comment]
@JanKoehnlein Awesome, thanks for clarifying!

**Review by ArthurSens — APPROVED** [review]
Rubber stamp 😬

**Comment by roboquat** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/gitpod-io/gitbot/pull/66#pullrequestreview-874413558" title="Approved">ArthurSens</a>*

The full list of commands accepted by this bot can be found [here](https://prow.gitpod-dev.com/command-help?repo=gitpod-io%2Fgitbot).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/gitpod-io/gitbot/blob/main/OWNERS)~~ [ArthurSens]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by roboquat** [comment]
@mads-hartmann: Updated the following 5 configmaps:
 * `customlabels` configmap in namespace `prow` at cluster `default` using the following files:
   - key `customlabels.yaml` using file ``
 * `groundwork` configmap in namespace `prow` at cluster `default` using the following files:
   - key `groundwork.yaml` using file ``
 * `plugins` configmap in namespace `prow` at cluster `default` using the following files:
   - key `plugins.yaml` using file `config/plugins.yaml`
 * `projectmanager` configmap in namespace `prow` at cluster `default` using the following files:
   - key `projectmanager.yaml` using file ``
 * `config` configmap in namespace `prow` at cluster `default` using the following files:
   - key `config.yaml` using file `config/config.yaml`


<details>

In response to [this](https://github.com/gitpod-io/gitbot/pull/66):

>## Description
>
>Once we have migrated to using GitHub for PR Review automation ([epic](https://github.com/gitpod-io/ops/issues/838)) we can remove a lot of the plugins that we current have from Prow.
>
>- assign (/assign)
>- blunderbuss (was supposed to automate review requests but was disabled)
>- verify-owners (would add the label `do-not-merge/invalid-owners-file` if the OWNERS or OWNER_ALIASES files were invalid)
>- owners-label (Would add labels based on owner)
>- approve (/approve which would add the approved label)
>- lgtm (/lgtm which would add the lgtm label)
>- groundwork (I believe the /schedule and other groundwork related commands we no longer use)
>- projectmanager (I believe this would move issues around, but we have since moved to the new GH Projects and don't rely on this)
>- goose, cat, and dog (/woof, /meow, and /honk)
>- heart (was unused, we never configured it)
>- yuks (/joke)
>- label (would allow .e.g `/kind bug` - instead use the native GH feature and just press 'l' when viewing a PR or issue which allows you to add labels) 
>- willkommen (was never used in gitpod-io/gitpod I believe)
>- customlabels (the labels used in gitpod-io/gitpod seems to no longer be relevant as we assign team labels based on PR Reviwers now)
>- observer (From Jan: "The observer was an early attempt to measure the throughput of our deployment pipeline. It's been obsoleted by Athenian")
>- help (/help command which added 'help wanted' or 'good first issue')
>
>## Related Issue(s)
>
>Fixes https://github.com/gitpod-io/ops/issues/845
>
>## How to test
>
>
>Merge and manually delete any k8s resources lingering around.
>
>## Release Notes
>
>```release-note
>NONE
>```
>
>## Documentation
>
>N/A


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mads-hartmann** [comment]
In the prow cluster I ran

```sh
kubectl -n prow delete cm willkommen projectmanager customlabels observer groundwork
```

**Pull request merged**
